name: release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3
      
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev
        
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm' # Set this to npm, yarn or pnpm.

      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install frontend dependencies
        run: pnpm install # change this to npm or pnpm depending on which one you use

      - name: Build app
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: __VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'tinkaros __VERSION__'
          releaseBody: |
            compiled files for __VERSION__:
            - **windows 10/11 => tinkaros___VERSION___x64_en-US.msi**
            - linux => tinkaros___VERSION___amd64.AppImage
            - linux-deb => tinkaros___VERSION___amd64.deb
          releaseDraft: true
          prerelease: false